/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2014 (12.0.5557)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/
USE [CelerityMarine_Stage]
GO
/****** Object:  Index [CELERITY_ST_CLIENTPREFERENCES_PK]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [CELERITY_ST_CLIENTPREFERENCES_PK] ON [dbo].[CELERITY_ST_CLIENTPREFERENCES]
GO
/****** Object:  Index [CELERITY_ST_CLIENT_NCI]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [CELERITY_ST_CLIENT_NCI] ON [dbo].[CELERITY_ST_CLIENT]
GO
/****** Object:  Index [NonClusteredIndex-ClientCode]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [NonClusteredIndex-ClientCode] ON [dbo].[CELERITY_ST_BROCHUREREQUEST]
GO
/****** Object:  Index [CELERITY_ST_BOOKINGS_NCI]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [CELERITY_ST_BOOKINGS_NCI] ON [dbo].[CELERITY_ST_BOOKINGS]
GO
/****** Object:  Index [CELERITY_ST_CLIENT_PK]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [CELERITY_ST_CLIENT_PK] ON [dbo].[CELERITY_ST_CLIENT] WITH ( ONLINE = OFF )
GO
/****** Object:  Index [CELERITY_ST_BOOKINGS_PK]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [CELERITY_ST_BOOKINGS_PK] ON [dbo].[CELERITY_ST_BOOKINGS] WITH ( ONLINE = OFF )
GO
/****** Object:  Index [CELERITY_ST_BOOKEDPASSENGERS_PK]    Script Date: 21/06/2018 10:58:59 ******/
DROP INDEX [CELERITY_ST_BOOKEDPASSENGERS_PK] ON [dbo].[CELERITY_ST_BOOKEDPASSENGERS] WITH ( ONLINE = OFF )
GO



/****** Object:  Index [CELERITY_ST_BOOKEDPASSENGERS_PK]    Script Date: 21/06/2018 10:58:59 ******/
CREATE CLUSTERED INDEX [CELERITY_ST_BOOKEDPASSENGERS_PK] ON [dbo].[CELERITY_ST_BOOKEDPASSENGERS]
(
	[BookRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [CELERITY_ST_BOOKINGS_PK]    Script Date: 21/06/2018 10:58:59 ******/
CREATE CLUSTERED INDEX [CELERITY_ST_BOOKINGS_PK] ON [dbo].[CELERITY_ST_BOOKINGS]
(
	[BookRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [CELERITY_ST_CLIENT_PK]    Script Date: 21/06/2018 10:58:59 ******/
CREATE CLUSTERED INDEX [CELERITY_ST_CLIENT_PK] ON [dbo].[CELERITY_ST_CLIENT]
(
	[ClientCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [CELERITY_ST_BOOKINGS_NCI]    Script Date: 21/06/2018 10:58:59 ******/
CREATE NONCLUSTERED INDEX [CELERITY_ST_BOOKINGS_NCI] ON [dbo].[CELERITY_ST_BOOKINGS]
(
	[BrandName] ASC,
	[Status] ASC
)
INCLUDE ( 	[BookRef],
	[BookingDate],
	[CancelledDate],
	[ConfirmDate],
	[BookingSourcePrimary]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [NonClusteredIndex-ClientCode]    Script Date: 21/06/2018 10:58:59 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ClientCode] ON [dbo].[CELERITY_ST_BROCHUREREQUEST]
(
	[ClientCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [CELERITY_ST_CLIENT_NCI]    Script Date: 21/06/2018 10:58:59 ******/
CREATE NONCLUSTERED INDEX [CELERITY_ST_CLIENT_NCI] ON [dbo].[CELERITY_ST_CLIENT]
(
	[ClientCode] ASC,
	[Brand] ASC
)
INCLUDE ( 	[Email1]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [CELERITY_ST_CLIENTPREFERENCES_PK]    Script Date: 21/06/2018 10:58:59 ******/
CREATE NONCLUSTERED INDEX [CELERITY_ST_CLIENTPREFERENCES_PK] ON [dbo].[CELERITY_ST_CLIENTPREFERENCES]
(
	[ClientCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
