/*

03/05/2018  TW  Prepare databases for deployment

Use truncation routines to clear down data tables
This should leave static data tables populated

CelerityMarine_Stage

NEPTUNE_Stage
   SL_BrochureName no longer required

HUBSPOT
   SL_BaseName do not deploy
      
   SL_HUBSPOT_FIELD_NAMES_DEPLOYMENT contains the currently agreed live HubSpot configuration property names
*/


USE CelerityMarine_Stage

GO

TRUNCATE TABLE TRT_Table_Row_Counts
TRUNCATE TABLE TRT_BOOKEDEXTRA
TRUNCATE TABLE TRT_BOOKEDACCOM
TRUNCATE TABLE TRT_BOOKEDFLIGHT
TRUNCATE TABLE TRT_BOOKINGPAX
TRUNCATE TABLE TRT_BOOKINGS
TRUNCATE TABLE TRT_BROCHUREREQUEST
TRUNCATE TABLE TRT_CLIENT
TRUNCATE TABLE TRT_CLIENTPREFERENCE
TRUNCATE TABLE TRT_MAILINGHISTORY
TRUNCATE TABLE TRT_EmailPreference
TRUNCATE TABLE TRT_File_Row_Counts
TRUNCATE TABLE TRT_Merged_Row_Counts

GO

TRUNCATE TABLE TRT_Sunsail_ST_EFMST
TRUNCATE TABLE TRT_Triton_ST_EFMST

GO

TRUNCATE TABLE CELERITY_ST_BOOKINGS
TRUNCATE TABLE CELERITY_ST_ACCOMMODATION
TRUNCATE TABLE CELERITY_ST_EXTRAS
TRUNCATE TABLE CELERITY_ST_FLIGHTS
TRUNCATE TABLE CELERITY_ST_BOOKEDPASSENGERS
TRUNCATE TABLE CELERITY_ST_CLIENT
TRUNCATE TABLE CELERITY_ST_CLIENTPREFERENCES
TRUNCATE TABLE CELERITY_ST_BROCHUREREQUEST
TRUNCATE TABLE CELERITY_ST_MAILINGHISTORY
    
GO

USE NEPTUNE_Stage

GO

TRUNCATE TABLE NEPTUNE_PASS
TRUNCATE TABLE NEPTUNE_BOOK
TRUNCATE TABLE NEPTUNE_ACCOMMODATION_REF
TRUNCATE TABLE NEPTUNE_ACCOMMODATION
TRUNCATE TABLE NEPTUNE_AGENT
TRUNCATE TABLE NEPTUNE_AIRCRAFT
TRUNCATE TABLE NEPTUNE_AIRLINE
TRUNCATE TABLE NEPTUNE_AVAIL
TRUNCATE TABLE NEPTUNE_AVBK
TRUNCATE TABLE NEPTUNE_BASE
TRUNCATE TABLE NEPTUNE_BKPRICE
TRUNCATE TABLE NEPTUNE_CHARTYPE
TRUNCATE TABLE NEPTUNE_EXRATE
TRUNCATE TABLE NEPTUNE_EXTRA
TRUNCATE TABLE NEPTUNE_EXTRAREF
TRUNCATE TABLE NEPTUNE_FLIGHT_ALLOC
TRUNCATE TABLE NEPTUNE_FLIGHT_REF
TRUNCATE TABLE NEPTUNE_PRICE_OPT
TRUNCATE TABLE NEPTUNE_PRODUCT
TRUNCATE TABLE NEPTUNE_REG_BASE
TRUNCATE TABLE NEPTUNE_SOURCE
TRUNCATE TABLE NEPTUNE_PRICE_DESC
TRUNCATE TABLE NEPTUNE_ORIGIN
TRUNCATE TABLE NEPTUNE_AREA
TRUNCATE TABLE NEPTUNE_MYUSER
TRUNCATE TABLE NEPTUNE_ACC_TYPE
TRUNCATE TABLE NEPTUNE_PAYMENT_DETAIL
TRUNCATE TABLE NEPTUNE_ROUTE
TRUNCATE TABLE NEPTUNE_PASSLINK
TRUNCATE TABLE NEPTUNE_FLIGHT
TRUNCATE TABLE NEPTUNE_AIRPORT
TRUNCATE TABLE NEPTUNE_INVOICE_COMPANY
TRUNCATE TABLE NEPTUNE_ACCNOTE
TRUNCATE TABLE NEPTUNE_INSTRUCT
TRUNCATE TABLE NEPTUNE_ROUTE_FLIGHT
TRUNCATE TABLE NEPTUNE_ROUTE_LINK
TRUNCATE TABLE NEPTUNE_FLTNOTE
TRUNCATE TABLE NEPTUNE_EMPL_UNAVAIL
TRUNCATE TABLE NEPTUNE_EMPL_AVAIL
TRUNCATE TABLE NEPTUNE_EMPLREF
TRUNCATE TABLE NEPTUNE_EXTRA_AVAIL

GO

TRUNCATE TABLE NEPTUNE_MAIL_CONTACT
TRUNCATE TABLE NEPTUNE_EBROC_NEWLETTERS
TRUNCATE TABLE NEPTUNE_FAMILY
TRUNCATE TABLE NEPTUNE_CLIENT_PREFERENCE
TRUNCATE TABLE NEPTUNE_REMBOOK

GO

TRUNCATE TABLE NEPTUNE_SFT_ALLOCATION
TRUNCATE TABLE ST_MARINE_ACCOMBOAT
TRUNCATE TABLE ST_MARINE_AVAILABLEPORTS
TRUNCATE TABLE ST_MARINE_AVAILPERWEEK
TRUNCATE TABLE ST_MARINE_BEDSTOSEATS
TRUNCATE TABLE ST_MARINE_BOATAVAILABILITY
TRUNCATE TABLE ST_MARINE_BOOKINGITEMS
TRUNCATE TABLE ST_MARINE_BOOKINGS
TRUNCATE TABLE ST_MARINE_BROCHURE_REQUEST
TRUNCATE TABLE ST_MARINE_CLIENT_PREFERENCE
TRUNCATE TABLE ST_MARINE_CLIENTS
TRUNCATE TABLE ST_MARINE_FBKG
TRUNCATE TABLE ST_MARINE_FITN
TRUNCATE TABLE ST_MARINE_FLIGHTINVENTORY
TRUNCATE TABLE ST_MARINE_HOTEL
TRUNCATE TABLE ST_MARINE_INSURANCE
TRUNCATE TABLE ST_MARINE_PAX
TRUNCATE TABLE ST_MARINE_PAXACC
TRUNCATE TABLE ST_MARINE_PAXBOAT
TRUNCATE TABLE ST_MARINE_PAXFLIGHT
TRUNCATE TABLE ST_MARINE_PAXFLIGHTDURATION
TRUNCATE TABLE ST_MARINE_PAYMENT
TRUNCATE TABLE ST_MARINE_REMBOOK
TRUNCATE TABLE ST_MARINE_SOLDPERWEEK

GO

USE HUBSPOT

GO

TRUNCATE TABLE ST_ERROR_LOG

GO
