INSERT INTO [CelerityMarine_stage].[dbo].[TRT_BookedExtraLookup]
(TRT_BookedExtraName,DerivedExtraName)
VALUES
 ('1 4pkt red bull-judith g','Beverage')
,('1 bombay sapphire-judith g','Beverage')
,('1 btl absolut vodka','Beverage')
,('1 btl moet en chandon-judith g','Beverage')
,('1 btl santa m.pinot grigio','Beverage')
,('1 btl santa margherita','Beverage')
,('1 btl southern comfort','Beverage')
,('1 c/s 16oz water-judith g','Beverage')
,('1 c/s amstel-judith g','Beverage')
,('1 c/s bvi spring-judith gumbs','Beverage')
,('1 c/s diet tonic-judith g','Beverage')
,('1 c/s highland 33 cl-judith g','Beverage')
,('1 c/s poland 16 oz-judith g','Beverage')
,('1 c/s redstripe-judith g.','Beverage')
,('1 cs 1.5 highland-judith gumbs','Beverage')
,('1 ea pineapple j.46oz-judith g','Beverage')
,('1 gal -pls coll judith gumbs','Beverage')
,('1 kotel vodka-judith g','Beverage')
,('1 pussers rum-judith g.','Beverage')
,('1 savon de mer-judith g','Beverage')
,('1 six p corona- judith gumbs','Beverage')
,('1 sundowner-pls coll judith g','Beverage')
,('10 c/s budlight beers-judith g','Beverage')
,('10lt water pls coll j gumbs','Beverage')
,('15 gals poland-judith gumbs','Beverage')
,('1cs poland&1cse bvi spr water','Beverage')
,('2 btls chivas regal-judith g','Beverage')
,('2 btls grand marnier','Beverage')
,('2 btls of jameson whisky-jg','Beverage')
,('2 btls pinot grigio','Beverage')
,('2 btls woodbridge chard.judith','Beverage')
,('2 c/s 16 oz water-judith g','Beverage')
,('2 c/s 16oz niagara-judith g','Beverage')
,('2 c/s 16oz water-judith g','Beverage')
,('2 c/s amstel-pls coll judith g','Beverage')
,('2 c/s bvi spring water','Beverage')
,('2 c/s bvi spring water-judith','Beverage')
,('2 c/s bvi spring-judith g','Beverage')
,('2 c/s coors light-judith gumbs','Beverage')
,('2 c/s gal water-judith g.','Beverage')
,('2 c/s k/j chardonnay','Beverage')
,('2 c/s poland 16oz-judith g','Beverage')
,('2 c/s presidente-judith g','Beverage')
,('2 ea orange juice 46oz-judith','Beverage')
,('2 grapefruit juice-judith g','Beverage')
,('2 six p-coors light-judith g','Beverage')
,('2 sundowners-pls coll judith g','Beverage')
,('2 sunrisers-pls coll judith g','Beverage')
,('3 bloody mary mix-judith gumbs','Beverage')
,('3 btls chardonnay k/j-judith g','Beverage')
,('3 c/s gal.water-judith g','Beverage')
,('3 c/s poland 16 oz-judith g','Beverage')
,('3 cranbeery juice-judith gumbs','Beverage')
,('3 ea guava j.46 oz judith g','Beverage')
,('3 mount gay-judith g','Beverage')
,('4 c/s carib - judith g','Beverage')
,('6gal water pls col j gumbs','Beverage')
,('Add bevs added at client req','Beverage')
,('Addt''l bev pls coll-judith g','Beverage')
,('Addt''l bev taken-coll-judith g','Beverage')
,('Addt''l beverages-pls coll','Beverage')
,('Addt''l bev-pls coll judith g','Beverage')
,('Addt''l bev-pls coll-judith g','Beverage')
,('Addt''l sunriser-judith g','Beverage')
,('Bev on line-pls coll judith g','Beverage')
,('Bev per judith','Beverage')
,('Bev pls col j gumbs','Beverage')
,('Bev pls coll j gumbs','Beverage')
,('Bev pls collect j gumbs','Beverage')
,('Beveraes-pls coll judith g','Beverage')
,('Beverages','Beverage')
,('Beverages - alcoholic','Beverage')
,('Beverages - non alcoholic','Beverage')
,('Beverages payable locally','Beverage')
,('Beverages taken-judith g','Beverage')
,('Beverages-ala carte-judith g','Beverage')
,('Beverages-from market-judith g','Beverage')
,('Beverages-judith g','Beverage')
,('Beverages-judith gumbs','Beverage')
,('Beverages-pls coll  judith g','Beverage')
,('Beverages-pls coll  judith g.','Beverage')
,('Beverages-pls coll judith g','Beverage')
,('Beverages-pls coll judith gh','Beverage')
,('Beverages-pls coll. judith g','Beverage')
,('Beverages-pls coll.judith g','Beverage')
,('Beverages-pls coll-judith g','Beverage')
,('Beverages-pls ref diff-judith','Beverage')
,('Beverages-pls refund','Beverage')
,('Bevs - pls collect','Beverage')
,('Bevs - plz collect','Beverage')
,('Bevs - plz collect $107.15','Beverage')
,('Bevs - plz collect $196.03','Beverage')
,('Bevs plz collect','Beverage')
,('Bevs taken locally - plz colle','Beverage')
,('Champagne - chilled','Beverage')
,('Champagne-chilled','Beverage')
,('Med drinks pack 4-6 pax','Beverage')
,('Med drinks pack 6-8 pax','Beverage')
,('Paid lss directly(no record)','Beverage')
,('Price promise bevs credit','Beverage')
,('Sunriser','Beverage')
,('Uk bevs - pls collect','Beverage')
,('Water purhase at sopher''s hole','Beverage')
,('Web beverages','Beverage')
,('1 birthday cake-judith g','Provisions')
,('1 chocolate cake-judith g','Provisions')
,('1 coco lopez-judith g','Provisions')
,('1 fruit basket-pls coll-judith','Provisions')
,('12 limes-pls.coll  judith g','Provisions')
,('2 bags ice-pls coll-judith g','Provisions')
,('2 bags of ice-judith gumbs','Provisions')
,('2 charcoals-pls coll judith g','Provisions')
,('2x3 easy otc-pls coll judith g','Provisions')
,('3 bags of ice-judith g','Provisions')
,('3 charcol-pls coll  judith g','Provisions')
,('3 floral arrangements','Provisions')
,('3 floral arrangemt-judith g','Provisions')
,('3 variety pkg cereal','Provisions')
,('30 limes-pls coll judith g','Provisions')
,('4 bags of ice-judith g.','Provisions')
,('4 toilet papers','Provisions')
,('4x6 easy on the cook-judith g','Provisions')
,('5 paper towels','Provisions')
,('6 bags of ice-judith g.','Provisions')
,('6 pringles-pls coll judith g','Provisions')
,('6 rolls toilet paper','Provisions')
,('6 yogurts-pls coll judith g.','Provisions')
,('A la carte list-judith gumbs','Provisions')
,('A la carte provisions-judith g','Provisions')
,('A la carte-bev-judith g','Provisions')
,('A la carte-judith g','Provisions')
,('A la carte-pls coll judith g','Provisions')
,('A la carte-pls coll-judith g','Provisions')
,('Additional prov-judith g','Provisions')
,('Addit''l food-judith g','Provisions')
,('Addtion''l food items-judith g','Provisions')
,('Addt''l food-pls coll-judith g','Provisions')
,('Addt''l prov taken','Provisions')
,('Birthd.cake-pls coll judith g.','Provisions')
,('Birthday cake-judith g','Provisions')
,('Birthday cake-pls coll judith','Provisions')
,('Cake','Provisions')
,('Charter starter 2/3 pax','Provisions')
,('Charter starter 4/5 pax','Provisions')
,('Charter starter 6/7 pax','Provisions')
,('Charter starter 8+ pax','Provisions')
,('Charter starter medium','Provisions')
,('Charter starter pack 4-5pax','Provisions')
,('Charter starter pack 8pax','Provisions')
,('Charter starter pack 8plus','Provisions')
,('Coffee filters','Provisions')
,('Consumables','Provisions')
,('Decorations-judith g','Provisions')
,('Dietary restrictions','Provisions')
,('Dine afloat provisioning','Provisions')
,('Dine ashore provisioning','Provisions')
,('Essential provisioning large','Provisions')
,('Essential provisioning regular','Provisions')
,('Floral arrangement','Provisions')
,('Floral arrangement - tropical','Provisions')
,('Floral arrangement-tropical','Provisions')
,('Flowers/champagne/gift','Provisions')
,('Food items taken-judith g','Provisions')
,('Food on line-pls coll judith g','Provisions')
,('Food-pls coll  judith g','Provisions')
,('Food-pls coll judith gumbs','Provisions')
,('Food-pls refund-judith g.','Provisions')
,('Fruit basket','Provisions')
,('Gift basket','Provisions')
,('Gift/fruit basket','Provisions')
,('Ice  fuel & consumables','Provisions')
,('Ice & water (included)','Provisions')
,('Items taken 01/27-judith g','Provisions')
,('Items taken 02/10-judith g','Provisions')
,('Items taken from deli-judith g','Provisions')
,('Items taken-02/21-judith g','Provisions')
,('Last orders','Provisions')
,('Last orders pack','Provisions')
,('Last orders provisioning','Provisions')
,('Limes/lemons-judith g','Provisions')
,('Med essential pack 4-6 pax','Provisions')
,('Med essential pack 6-8 pax','Provisions')
,('Med essential-pls coll judith','Provisions')
,('Med snack pack 4/5 pax','Provisions')
,('Med snack pack 4-5 pax','Provisions')
,('Med snack pack 6-8 pax','Provisions')
,('Med.essential-pls coll.judith','Provisions')
,('Online + starter kit-judith g','Provisions')
,('P.easy 2x5 pls coll  judith g','Provisions')
,('P.split 4x6-pls coll judith g','Provisions')
,('P.split 5x4-pls coll judith g.','Provisions')
,('Party items-pls coll judith g','Provisions')
,('Price promise p&b credit','Provisions')
,('Prov essent-pls coll-judith g','Provisions')
,('Prov plz collect','Provisions')
,('Prov taken locally - plz colle','Provisions')
,('Prov./beverage - service fee','Provisions')
,('Prov.-a la carte','Provisions')
,('Prov.-all afloat','Provisions')
,('Prov.-boxed lunch','Provisions')
,('Prov.-chtr.starter kit 2 3 pax','Provisions')
,('Prov.-chtr.starter kit 4 5 pax','Provisions')
,('Prov.-chtr.starter kit 6 7 pax','Provisions')
,('Prov.-chtr.starter kit 8 pax','Provisions')
,('Prov.-cook','Provisions')
,('Prov.-dine afloat','Provisions')
,('Prov.-dine ashore','Provisions')
,('Prov.-easy on cook','Provisions')
,('Prov.-easy on cook-personalize','Provisions')
,('Prov.-easy on the cook','Provisions')
,('Prov.-full','Provisions')
,('Prov.-half day','Provisions')
,('Prov.-offshore split prov pkg.','Provisions')
,('Prov.-personalized full','Provisions')
,('Prov.-personalized split','Provisions')
,('Prov.-skipper','Provisions')
,('Prov.-split','Provisions')
,('Prov.-surcharge/lobster','Provisions')
,('Provg per judith','Provisions')
,('Provg-skipper','Provisions')
,('Provision skipper','Provisions')
,('Provisioning','Provisions')
,('Provisioning savings','Provisions')
,('Provisions payable locally','Provisions')
,('Provisions-judith g','Provisions')
,('Provisions-pls coll judith g','Provisions')
,('Provisions-pls coll-judith g','Provisions')
,('Prov-pls coll judith gumbs','Provisions')
,('Provs-pls coll  judith g','Provisions')
,('Provs-pls coll-judith g','Provisions')
,('Skipper provg','Provisions')
,('Skipper provg  6@25','Provisions')
,('Snacks-from market-judith g','Provisions')
,('Split provisioning','Provisions')
,('Start up kit','Provisions')
,('Starter kit 4 pax-judith g.','Provisions')
,('Starter kit 4 pax-judith gumbs','Provisions')
,('Starter kit-pls coll  judith g','Provisions')
,('Starter kit-pls coll judith g','Provisions')
,('Sundowner','Provisions')
,('Web provisioning','Provisions')
,('Yacht catering starter pk sm','Provisions')
,('Med plan monos 41-52ft','Provisions')
,('Med plan monos 41-52ft 8 days+','Provisions')
,('Med plan monos up to 40ft','Provisions')
,('Med plan power cats','Provisions')
,('Med service plan >42 and cats','Provisions')
,('Med service plan >48 and cats','Provisions')
,('Med service plan >48''and cats','Provisions')
,('Med service plan 32 to 37''','Provisions')
,('Med service plan 38 to 41''','Provisions')
,('Med service plan 38 to 47''','Provisions')
,('Med service plan-weekend adj','Provisions')
,('Full provisioning','Provisions')
,('Get going large 6-8 pax','Provisions')
,('Get going medium 4-5 pax','Provisions')
,('Med breakfast pack 4-5 pax','Provisions')
,('Med breakfast pack 4/5 pax','Provisions')
,('Med breakfast pack 6-8 pax','Provisions')
,('Med breakfast pack 6/8 pax','Provisions')
,('Provisioning a la carte','Provisions')
,('Provisions','Provisions')
,('11pax ferry transfer 1 way','Transfers')
,('3departure transfers','Transfers')
,('4 depature transfers','Transfers')
,('4 roundtrip transfers','Transfers')
,('5arrival transfers','Transfers')
,('5pax one way','Transfers')
,('6pax logbay to airport','Transfers')
,('6pax taxi to long bay','Transfers')
,('6roundtrip taxi transfers','Transfers')
,('7departure transfers','Transfers')
,('8arrival transfers','Transfers')
,('8arrival transfers only','Transfers')
,('8departure transfers','Transfers')
,('Arr/dept transfers','Transfers')
,('Comp transfers','Transfers')
,('Departure 8pax','Transfers')
,('Departure transfer','Transfers')
,('Departure transfer 4pax','Transfers')
,('Departure transfers 5pax','Transfers')
,('Departure vouchers','Transfers')
,('Depature transfer','Transfers')
,('Drop off - scrub island','Transfers')
,('Drop off - trellis bay','Transfers')
,('Ferry only stt-tor adult o/way','Transfers')
,('Ferry only stt-tor child o/way','Transfers')
,('Ferry only stt-tor infant o/w','Transfers')
,('Ferry only tor-stt adult o/way','Transfers')
,('Ferry only tor-stt child o/way','Transfers')
,('Ferry only tor-stt infant o/w','Transfers')
,('Ferry- redhook-tor 9pm one-way','Transfers')
,('Ferry transfer 8pax','Transfers')
,('Ferry/taxi redhook-tor 7pm o/w','Transfers')
,('Ferry/taxi redhook-tor 9pm o/w','Transfers')
,('Ferry/taxi stt-tor 5:30 o/w','Transfers')
,('Ferry/taxi stt-tor 5:30 o/w a','Transfers')
,('Ferry/taxi stt-tor adult o/way','Transfers')
,('Ferry/taxi stt-tor child o/way','Transfers')
,('Ferry/taxi stt-tor infant o/w','Transfers')
,('Ferry/taxi tor-stt adult o/way','Transfers')
,('Ferry/taxi tor-stt child o/way','Transfers')
,('Ferry/taxi tor-stt infant o/w','Transfers')
,('Ferry-charlotteamalie-5:30 o/w','Transfers')
,('Ferry-redhook-tor 9pm child ow','Transfers')
,('French island visit','Transfers')
,('Hamilton island one-way','Transfers')
,('Hamilton island return','Transfers')
,('Interconnecting charge','Transfers')
,('O/s transfer','Transfers')
,('Prepaid transfers - roundtrip','Transfers')
,('Round trip transfer','Transfers')
,('Roundtrip','Transfers')
,('Roundtrip taxi vouchers 5pax','Transfers')
,('Roundtrip tranfers 5pax','Transfers')
,('Roundtrip transfers','Transfers')
,('Roundtrip transfers 9pax','Transfers')
,('Sunsail fast ferry adjustment','Transfers')
,('Taxi / ferry transfer package','Transfers')
,('Taxi for skipper','Transfers')
,('Taxi to long bay','Transfers')
,('Taxi transfer','Transfers')
,('Taxi transfer to w/e 5pax','Transfers')
,('Transfer','Transfers')
,('Transfer adjustment-trp','Transfers')
,('Transfer antalya airport/fetye','Transfers')
,('Transfer antalya airport/gok','Transfers')
,('Transfer ath arpt/kalamaki o/w','Transfers')
,('Transfer ath arpt/lavrion o/w','Transfers')
,('Transfer ath arpt/lfk base o/w','Transfers')
,('Transfer bodrum airport/fethiy','Transfers')
,('Transfer bodrum airport/gok','Transfers')
,('Transfer bodrum airport/orh','Transfers')
,('Transfer bodrum/turgetries','Transfers')
,('Transfer dalaman airport/fet','Transfers')
,('Transfer dalaman airport/feth','Transfers')
,('Transfer dalaman airport/fetye','Transfers')
,('Transfer dalaman airport/gok','Transfers')
,('Transfer dalaman airport/orh','Transfers')
,('Transfer fee','Transfers')
,('Transfer fenike/gok','Transfers')
,('Transfer fet/antalya airport','Transfers')
,('Transfer fet/bodrum airport','Transfers')
,('Transfer fet/dalaman airport','Transfers')
,('Transfer gok/antalya airport','Transfers')
,('Transfer gok/bodrum airport','Transfers')
,('Transfer gok/dalaman airport','Transfers')
,('Transfer igoumenitsa/lfk base','Transfers')
,('Transfer kalamaki/ath arpt o/w','Transfers')
,('Transfer lavrion/ath arpt o/w','Transfers')
,('Transfer lavrion/ath town o/w','Transfers')
,('Transfer lfk base/ath arpt o/w','Transfers')
,('Transfer lfk base/igoumenitsa','Transfers')
,('Transfer orh/bodrum airport','Transfers')
,('Transfer orh/dalaman airport','Transfers')
,('Transfer roundtrip airport/bas','Transfers')
,('Transfer switch in/op for fuel','Transfers')
,('Transfer to ferry 9pax','Transfers')
,('Transfer turgetries/bodrum','Transfers')
,('Transfer voucher','Transfers')
,('Transfers','Transfers')
,('Transfers - one way','Transfers')
,('Transfers - one-way','Transfers')
,('Transfers - roundtrip','Transfers')
,('Transfers one way - prepaid','Transfers')
,('Transfers one way airport/base','Transfers')
,('Transfers ow airport-base','Transfers')
,('Transfers roundtrip - prepaid','Transfers')
,('Transfers rt airport-base','Transfers')
,('Ferry/shuttle stt-tor ad o/w','Transfers')
,('Ferry/shuttle stt-tor ch o/w','Transfers')
,('Ferry/shuttle stt-tor inf o/w','Transfers')
,('Ferry/shuttle tor-stt ad o/w','Transfers')
,('Ferry/shuttle tor-stt ch o/w','Transfers')
,('Ferry/shuttle tor-stt ch o/way','Transfers')
,('Ferry/shuttle tor-stt inf o/w','Transfers')
,('Private taxi transfer','Transfers')
,('Shuttle only airport-sto ad ow','Transfers')
,('Shuttle only airport-sto ch ow','Transfers')
,('Shuttle only airport-tor ad ow','Transfers')
,('Shuttle only airport-tor ch ow','Transfers')
,('Shuttle only airport-trp ad ow','Transfers')
,('Shuttle only airport-trp ch ow','Transfers')
,('Shuttle only sto-airport ad ow','Transfers')
,('Shuttle only sto-airport ch ow','Transfers')
,('Shuttle only tor-airport ad ow','Transfers')
,('Shuttle only tor-airport ch ow','Transfers')
,('Shuttle only trp-airport ad ow','Transfers')
,('Shuttle only trp-airport ch ow','Transfers')
,('Shuttle r/town ferry-tor ad ow','Transfers')
,('Shuttle r/town ferry-trp ad ow','Transfers')
,('Shuttle sto-r/town ferry ad ow','Transfers')
,('Shuttle tor-r/town ferry ad ow','Transfers')
,('2 man kayak last stop sport','Kayak')
,('2 man less kayak','Kayak')
,('2 man less kyak','Kayak')
,('Double hobie kayak','Kayak')
,('Double kayak 4day rental','Kayak')
,('For 1 man kayak','Kayak')
,('For kayak as per last stop spo','Kayak')
,('For kayak as per renport','Kayak')
,('For tango vision kyak','Kayak')
,('For(2) 2 man kayak and 2 float','Kayak')
,('Kayak - 1 man','Kayak')
,('Kayak - 2 man','Kayak')
,('Kayak - tango vision','Kayak')
,('Kayak 1 man','Kayak')
,('Kayak 1-man','Kayak')
,('Kayak 2 man','Kayak')
,('Kayak 2 man less','Kayak')
,('Kayak request','Kayak')
,('Kayak requested','Kayak')
,('Kayak-1 man  lss','Kayak')
,('Kayak-2 man  lss','Kayak')
,('Lss double kayak','Kayak')
,('Lss doublekayak.locally','Kayak')
,('Lss refund 2man kayak','Kayak')
,('Ocean kayak','Kayak')
,('Ocean kayak-single','Kayak')
,('Single kayak(to creditbalance)','Kayak')
,('Adj client got paddle board','Paddle Board')
,('Ajustment for paddle board','Paddle Board')
,('Default code for lssstandup','Paddle Board')
,('For stand up paddle board','Paddle Board')
,('Stand up paddle board','Paddle Board')
,('Stand up paddleboards','Paddle Board')
,('Stand-up paddle board','Paddle Board')
,('Standup paddleboard','Paddle Board')
,('Sup - stand up paddleboard','Paddle Board')
,('Additional dinghy & outboard','Dinghy and/or Outboard')
,('Dinghy ladder request','Dinghy and/or Outboard')
,('Dinghy outboard rental','Dinghy and/or Outboard')
,('Dinghy rental','Dinghy and/or Outboard')
,('Dinghy rental - extra','Dinghy and/or Outboard')
,('Dinghy request-island time ltd','Dinghy and/or Outboard')
,('Extra dighy','Dinghy and/or Outboard')
,('For 2nd dingy rental','Dinghy and/or Outboard')
,('For extra dingy rental refund','Dinghy and/or Outboard')
,('Outboard hire per week','Dinghy and/or Outboard')
,('Outboard motor','Dinghy and/or Outboard')
,('Quoted rate for 2nd dghyrental','Dinghy and/or Outboard')
,('Extra dinghy & outboard','Dinghy and/or Outboard')
,('Damage waiver','Damage Waiver')
,('Damage waiver <= 41''- low ded.','Damage Waiver')
,('Damage waiver <= 41''- no ded.','Damage Waiver')
,('Damage waiver <=35'' - low ded.','Damage Waiver')
,('Damage waiver 36''- 43''low ded.','Damage Waiver')
,('Damage waiver 36''-43''high ded.','Damage Waiver')
,('Damage waiver 36''-43''-low ded','Damage Waiver')
,('Damage waiver germany','Damage Waiver')
,('Damage waiver<= 35''- low ded.','Damage Waiver')
,('Damage waiver<= 41''- high ded.','Damage Waiver')
,('Damage waiver<=42''+cats-noded.','Damage Waiver')
,('Damage waiver>=42''+cat-low ded','Damage Waiver')
,('Damage waiver>=42''+cats-noded.','Damage Waiver')
,('Damage waiver>=44''+cats-lowded','Damage Waiver')
,('Damage waiver>42''+cats-no ded','Damage Waiver')
,('Damagewaiver>=42''+cat-high ded','Damage Waiver')
,('Yacht damage waiver - 5800','Damage Waiver')
,('Yacht damage waiver <=35''','Damage Waiver')
,('Yacht damage waiver >=44''+cat','Damage Waiver')
,('Yacht damage waiver 36''-43''','Damage Waiver')
,('Yacht damage waiver 41 - 53ft','Damage Waiver')
,('Yacht damage waiver 41-52 ft','Damage Waiver')
,('Yacht damage waiver 41-52ft','Damage Waiver')
,('Yacht damage waiver 53-57 ft','Damage Waiver')
,('Yacht damage waiver 53-57ft','Damage Waiver')
,('Yacht damage waiver up to 40ft','Damage Waiver')
,('Yacht damage','Damage Waiver')
,('Accommodation','Hotel')
,('Blue waters hotel','Hotel')
,('Hotel - captain oliver''s fee','Hotel')
,('Hotel accommodation','Hotel')
,('Hotel adjustment','Hotel')
,('Hotel adjustment-abaco beach','Hotel')
,('Hotel adjustment-capt.olivers','Hotel')
,('Hotel adjustment-conch inn','Hotel')
,('Hotel adjustment-mariner inn','Hotel')
,('Hotel adjustment-south waters','Hotel')
,('Hotel adjustment-treasure isle','Hotel')
,('Hotel beds adjustment','Hotel')
,('Hotel charge','Hotel')
,('Hotel or evening start savings','Hotel')
,('Hotel tax','Hotel')
,('Hotel tax adjust','Hotel')
,('Hotel tax adjust-mariner inn','Hotel')
,('Hotel tax adjust-treasure isle','Hotel')
,('Room out of service - capt olv','Hotel')
,('Room out of service - conch','Hotel')
,('Room out of service - not ti','Hotel')
,('Room out of service - southwat','Hotel')
,('Room out of service - ti only','Hotel')
,('Room out of service-laru beya','Hotel')
,('Room out of service-true blue','Hotel')
,('Room supplement','Hotel')
,('Seaview supplement','Hotel')
,('Single occupancy supplemt','Hotel')
,('Sleep aboard','Hotel')
,('Sleep aboard - 2 cabins','Hotel')
,('Sleep aboard - 3+ cabins','Hotel')
,('Sleepaboard','Hotel')
,('Sole occupancy supplement','Hotel')
,('Stateroom catamaran-sgl','Hotel')
,('Stateroom single occ. supp.','Hotel')
,('Stateroom-catamaran sgl','Hotel')
,('Additional sports cover','Travel Insurance')
,('Adult (65-79) up to 10 days','Travel Insurance')
,('Adult (65-79) up to 17 days','Travel Insurance')
,('Adult annual insurance','Travel Insurance')
,('Adult ins upto 10days','Travel Insurance')
,('Adult ins upto 17days','Travel Insurance')
,('Annual world adult ins','Travel Insurance')
,('Canx ins & ass 2000-2999','Travel Insurance')
,('Canx ins & ass 4000-4999','Travel Insurance')
,('Canx ins & ass 5000-5999','Travel Insurance')
,('Canx ins & ass 6000-9999','Travel Insurance')
,('Charter care protection plan','Travel Insurance')
,('Child ins upto 10days','Travel Insurance')
,('Couple ins upto 10days','Travel Insurance')
,('Couple ins upto 17days','Travel Insurance')
,('Days insurance','Travel Insurance')
,('Family ins upto 10days','Travel Insurance')
,('Over 65-79 couple ins 31days','Travel Insurance')
,('Over 65''s ins upto 10days','Travel Insurance')
,('P & i insurance','Travel Insurance')
,('Security insurance','Travel Insurance')
,('Security insurance >= 36''','Travel Insurance')
,('Sunsail care plan','Travel Insurance')
,('Teans ins upto 10days','Travel Insurance')
,('Teens ins upto 10days','Travel Insurance')
,('Teens ins upto 17days','Travel Insurance')
,('Travel insurance cancel fee','Travel Insurance')
,('Trip cancellation insurance','Travel Insurance')
,('Trip insurance','Travel Insurance')
,('World adult ins upto 10days','Travel Insurance')
,('World adult ins upto 17days','Travel Insurance')
,('World adult ins upto 31days','Travel Insurance')
,('World child ins upto 17days','Travel Insurance')
,('World couple ins upto 10days','Travel Insurance')
,('World couple ins upto 17days','Travel Insurance')
,('World couple ins upto 31days','Travel Insurance')
,('World couples ins upto 10days','Travel Insurance')
,('World couples ins upto 31days','Travel Insurance')
,('World couples ins upto 365 dys','Travel Insurance')
,('World family ins up to 10 days','Travel Insurance')
,('World family ins up to 17 days','Travel Insurance')
,('World insurance upto 17days','Travel Insurance')
,('World over 65 ins upto 31days','Travel Insurance')
,('World teen ins upto 17days','Travel Insurance')
,('Worldwide couple insur 10 day','Travel Insurance')
,('Worldwide insur couple <10 day','Travel Insurance')
,('Worldwide insur couple <18 day','Travel Insurance')
,('Worldwide insur senior <17 day','Travel Insurance')
,('Worldwide insur senior <18 day','Travel Insurance')
,('Worldwide insur teen <18 days','Travel Insurance')
,('Insurance - up to 12 days','Travel Insurance')
,('Early boarding','Early boarding/ Evening starts')
,('Early riser','Early boarding/ Evening starts')
,('Evening start','Early boarding/ Evening starts')
,('Evening start','Early boarding/ Evening starts')
,('Evening start - owners','Early boarding/ Evening starts')
,('Evening start credit','Early boarding/ Evening starts')
,('Price promise evening start','Early boarding/ Evening starts')
,('Quoted  for evening start','Early boarding/ Evening starts')
,('Early check-in','Early boarding/ Evening starts')
,('1 float','Floating mats')
,('2 float','Floating mats')
,('2 float last stop sport','Floating mats')
,('2 floats','Floating mats')
,('Float','Floating mats')
,('For 2 float','Floating mats')
,('Child netting','Side netting')
,('Child restraint netting','Side netting')
,('Child restraint netting < 42''','Side netting')
,('Child restraint netting > 43''','Side netting')
,('Blue cushion','Deck cushions')
,('Lost blue cushion','Deck cushions')
,('Lost cushion','Deck cushions')
,('For dockage fees','Mooring fees')
,('Port fee','Mooring fees')
,('Virgin anchorages','Mooring fees')
,('One way charge (comm)','One way supplement')
,('One way delivery fee','One way supplement')
,('One way drop off - tuamotus','One way supplement')
,('One way drop off fee','One way supplement')
,('One way drop off fee-bora bora','One way supplement')
,('One way transfer','One way supplement')
,('Delivery peter island','One way supplement')
,('Delivery scrub/trellis','One way supplement')
,('Delivery st thomas/usvi','One way supplement')
,('One way drop martinique crewed','One way supplement')
,('One way ibiza - palma','One way supplement')
,('Boat cleaning fee','Cleaning')
,('Clean up fee','Cleaning')
,('Cleaner','Cleaning')
,('Cleaning','Cleaning')
,('Cleaning & ancillary services','Cleaning')
,('Cleaning charge','Cleaning')
,('Cleaning fee >42 and cats','Cleaning')
,('Cleaning fee >48 and cats','Cleaning')
,('Cleaning fee 30'' to 37''','Cleaning')
,('Cleaning fee 32'' to 37''','Cleaning')
,('Cleaning fee 38 to 41''','Cleaning')
,('Cleaning fee 38 to 47''','Cleaning')
,('Clean-up fee','Cleaning')
,('Clean-up fee < 40''','Cleaning')
,('Clean-up fee > 40''','Cleaning')
,('End cleaning 36-43ft','Cleaning')
,('End cleaning 42ft & up + cats','Cleaning')
,('End cleaning 44ft & up + cats','Cleaning')
,('End cleaning up to 35ft','Cleaning')
,('End cleaning up to35ft','Cleaning')
,('Yacht cleaning','Cleaning')
,('Cleanup fee','Cleaning')
,('Consumables & clean-up','Cleaning')
,('3 dive less tank package','Dive package')
,('Crewed yacht diving pkg','Dive package')
,('Cy scuba diving','Dive package')
,('Dive - 1 tank  diver  pkg','Dive package')
,('Dive - 2 tank  scuba  pkg','Dive package')
,('Dive - 2 tank only  tank  pkg','Dive package')
,('Dive discover scuba-sail carib','Dive package')
,('Dive interest','Dive package')
,('Dive package atlantic','Dive package')
,('Dive package atlantis','Dive package')
,('Dive package explorer','Dive package')
,('Dive package-crewed yacht','Dive package')
,('Dive package-crewed yacht-full','Dive package')
,('Dive package-crewed yacht-half','Dive package')
,('Dive pkg sail caribbean divers','Dive package')
,('Dive-lss diver pkg','Dive package')
,('Dive-lss scuba pkg','Dive package')
,('Dive-lss tank pkg','Dive package')
,('For 1 scuba package','Dive package')
,('Padi rms rhone specialty','Dive package')
,('Scuba diving','Dive package')
,('Fishing license','Angling licence (BVIs)')
,('Fishing vessel registration','Angling licence (BVIs)')
,('2 spinning fishing rod','Angling gear')
,('2day refund 1trolling pkg','Angling gear')
,('Fishing - miscellaneous','Angling gear')
,('Fishing - penn int''l 50vw pkg.','Angling gear')
,('Fishing - spinning rod','Angling gear')
,('Fishing - trolling rod','Angling gear')
,('Fishing gear','Angling gear')
,('Fishing rod and reel','Angling gear')
,('Fishing spinning reel/rod pkg','Angling gear')
,('Fishing spinning rod refund','Angling gear')
,('Fishing starter kit','Angling gear')
,('Fishing trolling reekl/rod pkg','Angling gear')
,('Fishing trolling reel/rod pkg','Angling gear')
,('Fishing:fin-nor combo packages','Angling gear')
,('Trolling fishing rod','Angling gear')
,('Fishing gear trolling','Angling gear')
,('Fishing spinning reel','Angling gear')
,('Aug/sept fuel credit','Fuel paid in advance')
,('For diesel','Fuel paid in advance')
,('For fuel','Fuel paid in advance')
,('Free fuel','Fuel paid in advance')
,('Free fuel offer','Fuel paid in advance')
,('Fuel','Fuel paid in advance')
,('Fuel cats 41ft+','Fuel paid in advance')
,('Fuel cats up  to 40ft','Fuel paid in advance')
,('Fuel charge >=42''','Fuel paid in advance')
,('Fuel charge >=42'' and cats','Fuel paid in advance')
,('Fuel charge >=44'' and cats','Fuel paid in advance')
,('Fuel charge 34'' and under','Fuel paid in advance')
,('Fuel charge 35'' and under','Fuel paid in advance')
,('Fuel charge 35'' to 41''','Fuel paid in advance')
,('Fuel charge 36'' to 43''','Fuel paid in advance')
,('Fuel monos  41ft+','Fuel paid in advance')
,('Fuel monos up to 40ft','Fuel paid in advance')
,('Fuel supplement','Fuel paid in advance')
,('Fuel surcharge > 48 and cats','Fuel paid in advance')
,('Gasoline/oil refund leonard','Fuel paid in advance')
,('Power fuel offer','Fuel paid in advance')
,('Prepaid fuel charges','Fuel paid in advance')
,('Fuel charge >= 46''+cats','Fuel paid in advance')
,('Fuel charge all cats','Fuel paid in advance')
,('Fuel charge = cats','Fuel paid in advance')
,('Fuel charge cats <= 40''','Fuel paid in advance')
,('Fuel charge cats > 40''','Fuel paid in advance')
,('Fuel charge monos <= 40''','Fuel paid in advance')
,('Fuel charge monos > 40''','Fuel paid in advance')
,('Additional crew','Cook and Hostess')
,('Additional crewed expenses','Cook and Hostess')
,('Bahamas crewed offer','Cook and Hostess')
,('Caribbean crewed email offer','Cook and Hostess')
,('Caribbean crewed free day','Cook and Hostess')
,('Caribbean crewed offer','Cook and Hostess')
,('Caribbean crewed quote offer','Cook and Hostess')
,('Caribbean crewed special','Cook and Hostess')
,('Caribbean crewed summer offer','Cook and Hostess')
,('Cook','Cook and Hostess')
,('Crew gratuity - crewed yacht','Cook and Hostess')
,('Crew gratuity- crewed tip','Cook and Hostess')
,('Crew gratuity- crewed yacht','Cook and Hostess')
,('Crew gratuity-bareboat','Cook and Hostess')
,('Crew gratuity-bb','Cook and Hostess')
,('Crew gratuity-cy','Cook and Hostess')
,('Crew request','Cook and Hostess')
,('Crew tip - bareboat','Cook and Hostess')
,('Crew tip - crewed yacht','Cook and Hostess')
,('Crewed june special','Cook and Hostess')
,('Crewed lates','Cook and Hostess')
,('Crewed may special','Cook and Hostess')
,('Crewed offer','Cook and Hostess')
,('Crewed savings','Cook and Hostess')
,('Crewed special','Cook and Hostess')
,('Crewed special march 16','Cook and Hostess')
,('Crewed winter kickoff','Cook and Hostess')
,('Crewed yacht - usvi','Cook and Hostess')
,('Hostess','Cook and Hostess')
,('Cash for crewed','Cook and Hostess')
,('Crew gratuity - crewed','Cook and Hostess')
,('Crew member full day','Cook and Hostess')
,('Exotics crewed','Cook and Hostess')
,('Fall crewed','Cook and Hostess')
,('Prov.-cook/host','Cook and Hostess')
,('Steward','Cook and Hostess')
,('Winter crewed','Cook and Hostess')
,('½ price flot fee >=44 & cats','Flotilla')
,('½ price flot fee 35 and under','Flotilla')
,('½ price flot fee 36 to 43 ft.','Flotilla')
,('Flotilla','Flotilla')
,('Flotilla - boat u.s.','Flotilla')
,('Flotilla - owners','Flotilla')
,('Flotilla fee >=44'' and cats','Flotilla')
,('Flotilla fee 35'' and under','Flotilla')
,('Flotilla fee 36'' to 43''','Flotilla')
,('Flotilla fee 41'' to 52''','Flotilla')
,('Flotilla fee 53'' +','Flotilla')
,('Flotilla fee cats','Flotilla')
,('Flotilla fee up to 40 ft','Flotilla')
,('Flotilla supplement','Flotilla')
,('Flotilla hero package','Flotilla Speciality')
,('Flotilla zero package','Flotilla Speciality')
,('Whale shark flotilla','Flotilla Speciality')
,('Wine & sail flotilla 2016','Flotilla Speciality')
,('Wine & sail flotilla 2017','Flotilla Speciality')
,('Wine flotilla <35ft','Flotilla Speciality')
,('Wine flotilla >44''& cats','Flotilla Speciality')
,('Wine flotilla 36 - 43ft','Flotilla Speciality')
,('Bvi rum flotilla package','Flotilla Speciality')
,('Sail and eat flotilla','Flotilla Speciality')
,('Taste of paradise flotilla','Flotilla Speciality')
,('Wine & sail flotilla','Flotilla Speciality')
,('Late check out','Late check out')
,('Late fee','Late check out')
,('For renport modem','Wifi')
,('For renport surf modem pk','Wifi')
,('For renport usb modem','Wifi')
,('For surf usb modem pak','Wifi')
,('For usb moden','Wifi')
,('For usb surf modem pak renport','Wifi')
,('Renport modem','Wifi')
,('Renport modem  pak','Wifi')
,('Renport modem as per catherine','Wifi')
,('Renport modem pak','Wifi')
,('Renport refund modem pak','Wifi')
,('Renport surf router pak','Wifi')
,('Renport usb modem','Wifi')
,('Renport-surf 4g mobile pak','Wifi')
,('Renport-surf router pak','Wifi')
,('Renport-surf usb free pak','Wifi')
,('Renport-surf usb modem pak','Wifi')
,('Renport-surf usb moden pak','Wifi')
,('Surf mi-fi hotspot pkg(on spot','Wifi')
,('Usb modem','Wifi')
,('Renport-smart 4g mobile pak','Wifi')
,('Renport-smart 4g pak','Wifi')
,('Renport - surf 4g mobile pak','Wifi')
,('Renport-surf 4g router pak','Wifi')
,('Renport-surf 4g usb modem pak','Wifi')
,('For renport blender','Electronics')
,('For renport buoy pak','Electronics')
,('Renport blender pak','Electronics')
,('Renport blender plus pak','Electronics')
,('Renport entertainment package','Electronics')
,('Renport inverter','Electronics')
,('Renport power pak inverter','Electronics')
,('Renport power pak invertor','Electronics')
,('Renport product as per renport','Electronics')
,('Renport-beaconpak-playstation2','Electronics')
,('Renport-beam pak entertainment','Electronics')
,('Renport-blender pack','Electronics')
,('Renport-blender pak','Electronics')
,('Renport-blender plus pak','Electronics')
,('Renport-buoy pak-dvd/tv','Electronics')
,('Renport-power pak plus','Electronics')
,('Renport-power pak-inverter','Electronics')
,('Renport-sail pak-notebook pc','Electronics')
,('Renport-wave pak','Electronics')
,('Renport-wave plus pak-jukebox','Electronics')
,('Renport-wave scene pak','Electronics')
,('Renport-wave sound adaptr link','Electronics')
,('Renport-wave sound plus pak','Electronics')
,('Renport-beaconpak-playstation4','Electronics')
,('Renport-blender juice pak','Electronics')
,('Renport-brew espresso pak','Electronics')
,('Renport-sail plus pak','Electronics')
,('Renport-wavesound plus pak','Electronics')
,('Beverage','Ancilliaries')
,('Provisions','Ancilliaries')
,('Kayak','Ancilliaries')
,('Paddle Board','Ancilliaries')
,('Dinghy and/or Outboard','Ancilliaries')
,('Floating mats','Ancilliaries')
,('Side netting','Ancilliaries')
,('Deck cushions','Ancilliaries')
,('Dive package','Ancilliaries')
,('Angling licence (BVIs)','Ancilliaries')
,('Angling gear','Ancilliaries')
,('Wifi','Ancilliaries')
,('Electronics','Ancilliaries')

GO